version: "3.0"
services:
  server:
    image: ademattos/portal-server:latest
    container_name: server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:300
    networks:
      - backend

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./webroot:/var/www/certbot
      - ./dhparam:/etc/ssl/certs
    depends_on:
      - server
    networks:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./webroot:/var/www/certbot
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/certbot --email anthony.demattos@netonomy.io --agree-tos --no-eff-email --force-renewal -d api-dev.netonomy.io -d www.api-dev.netonomy.io

volumes:
  certbot-etc:
  certbot-var:

networks:
  backend:
